---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 0c570d1ba90491dc5b62b6f1e913ac79f446f3ec
    fabric8.io/git-branch: migrate-workshop
  labels:
    expose: "true"
    app: backend
    provider: fabric8
    version: 3.0.0-SNAPSHOT
    group: org.jboss.examples.eap
  name: backend
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend
    provider: fabric8
    group: org.jboss.examples.eap
